name: publish

on:
  push:
    tags:
      - "*"

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node 16.17.0
        uses: actions/setup-node@v3
        with:
          node-version: 16.17.0

      - name: Setup Bun (for deps)
        uses: antongolub/action-setup-bun@v1
        with:
          bun-version: 0.1.11
          cache: true
          cache-bin: true

      - name: Install Dependencies
        run: bun install

      - name: Build With Typescript
        run: bun run build

      - name: Push to NPM
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_AUTH_TOKEN }}
